// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_probability_cpp
NumericMatrix compute_probability_cpp(NumericMatrix Y_d, NumericVector Beta, NumericMatrix mu, NumericMatrix phi, NumericVector Q_J, NumericVector t_d, NumericVector t_star_J, NumericVector sigma_star_2_J);
RcppExport SEXP _chdp_compute_probability_cpp(SEXP Y_dSEXP, SEXP BetaSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP Q_JSEXP, SEXP t_dSEXP, SEXP t_star_JSEXP, SEXP sigma_star_2_JSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Y_d(Y_dSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Beta(BetaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Q_J(Q_JSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t_d(t_dSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t_star_J(t_star_JSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma_star_2_J(sigma_star_2_JSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_probability_cpp(Y_d, Beta, mu, phi, Q_J, t_d, t_star_J, sigma_star_2_J));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_chdp_compute_probability_cpp", (DL_FUNC) &_chdp_compute_probability_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_chdp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
